Background_Management_Systeme/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import user_login, depart, user, prettynum, admin, task, order

urlpatterns = [
    # path('admin/', admin.site.urls),

    # ！ 用户登录
    # 登陆前页面展示，暂时不需要
    # path('before/login/', user_login.before_login),
    path('login/', user_login.login),
    path('image/code/', user_login.image_code),
    path('logout/', user_login.logout),

    # ！ 部门管理
    path('depart/list/', depart.list),
    path('depart/add/', depart.add),
    path('depart/<int:nid>/edit/', depart.edit),
    path('depart/delete/', depart.delete),

    # ！ 员工信息管理
    path('user/list/', user.list),
    path('user/add/', user.add),
    path('user/<int:nid>/edit/', user.edit),
    path('user/delete/', user.delete),

    # ！ 靓号信息管理
    path('prettynum/list/', prettynum.list),
    path('prettynum/add/', prettynum.add),
    path('prettynum/<int:nid>/edit/', prettynum.edit),
    path('prettynum/delete/', prettynum.delete),

    # ！ 管理员信息管理
    path('admin/list/', admin.list),
    path('admin/add/', admin.add),
    path('admin/<int:nid>/edit/', admin.edit),
    path('admin/delete/', admin.delete),

    # ！ 任务管理
    path('task/add/', task.add),
    path('task/list/', task.list),
    path('task/add_ajax/', task.add_ajax),
    path('task/<int:nid>/edit/', task.edit),
    path('task/delete/', task.delete),

    # ！ 订单管理
    path('order/list/', order.list),
    path('order/add/', order.add),
    path('order/<int:nid>/edit/', order.edit_normal),
    path('order/edit_ajax/', order.edit_ajax),
    path('order/edit_ajax_return/', order.edit_ajax_return),
    path('order/delete/', order.delete_normal),
    path('order/delete_ajax/', order.delete_ajax),
]

app01/models.py
from django.db import models

# Create your models here.

# 创建管理员数据表
class Admin(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    # 关联表格页面展示问题：定义str函数，即可解决输出为object对象的问题
    def __str__(self):
        return self.name
        
        
# 创建部门数据表
class Department(models.Model):
    name = models.CharField(verbose_name='部门名称', max_length=32)
    
    # 实例化对象打印的时候，就展示输出self.title的内容
    def __str__(self):
        return self.name


# 创建用户数据表
class UserInfo(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account_balance = models.DecimalField(verbose_name='账户余额',
                                          max_digits=10, 
                                          decimal_places=2,
                                          default=0)
    create_time = models.DateField(verbose_name='入职时间')
    user_department = models.ForeignKey(verbose_name='员工所属部门', to="Department", to_field="id",
                                        on_delete = models.CASCADE)

    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)



# 创建靓号数据表
class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格')
    level_choices = (
        (1, '一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级')
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices, default=1)
    
    status_choices = (
        (1, '已占用'),
        (2, '未占用')
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=2)
    

# 创建任务类数据表
class Task(models.Model):
    level_choices = (
        (1, '紧急'),
        (2, '重要'),
        (3, '常规'),
    )
    level = models.SmallIntegerField(verbose_name='任务级别', choices=level_choices, default=3)
    task_title = models.CharField(verbose_name='任务标题', max_length=64)
    task_content = models.TextField(verbose_name='任务内容')
    Person_in_Charge = models.ForeignKey(verbose_name='负责人', to='Admin', on_delete=models.CASCADE)
    

# 订单设计
class Order(models.Model):
    oid = models.CharField(verbose_name='订单号', max_length=64)
    name = models.CharField(verbose_name='订单名称', max_length=32)
    price = models.IntegerField(verbose_name='价格')
    
    status_choices = (
        (1, '待支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    
    # 本该跟用户关联，用户数据太多，就先跟管理员关联
    admin = models.ForeignKey(verbose_name='管理员', to='Admin', on_delete=models.CASCADE)
    
    
    

app01/views/Layout_Function.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models

from app01.utils.pagination import Pagination
from app01.utils.My_ModelForm import *

class Views_List_HTML():
    def __init__(self):
        pass
    
    def version_1(self, request, Models_Category, ModelForm_Category_list):
        form_search = ModelForm_Category_list()
        choices_list = {}
        
        search_key = request.GET.get('search_key')
        search_result = request.GET.get('search_data', '')
        if search_result:
            for field in form_search:
                if field.label == search_key:
                    
                    choices_list['{}__contains'.format(field.name)] = search_result
        
        data_list_selected = Models_Category.objects.filter(**choices_list)  # filter搜索条件如果为空，则等价于.all()
        
        pagination_object = Pagination(request, data_list_selected)
        context = {
            'data_list':pagination_object.data_list_PerPageShow,
            'search_result':search_result,
            'page_string':pagination_object.Html_Pagination(),
            'form_search':form_search
        }
        return context


class Data_Delete():
    def __init__(self):
        pass
    
    def Delete(self, Models_Category):
        Models_Category.objects.all().delete()

app01/views/admin.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models

from app01.utils.pagination import Pagination
from app01.utils.My_ModelForm import *
from app01.utils.database_data_process import Data_Create

from app01.views.Layout_Function import *

# ！ 常量
STR_Name = '管理员信息'

Models_Category = models.Admin
ModelForm_Category_list = AdminModelForm_list
ModelForm_Category_add = AdminModelForm_add
ModelForm_Category_edit = AdminModelForm_edit

def list(request):
    # 创建数据
    # Data_Create().create_data_num = 10
    # Data_Create().admin()

    context = Views_List_HTML().version_1(request, Models_Category, ModelForm_Category_list)
    context['ModelForm_title'] = '新建' + STR_Name
    context['Table_title'] = STR_Name + '列表'
    return render(request, 'admin/list.html', context)


def add(request):
    if request.method == "GET":
        form = ModelForm_Category_add()
        context = {'form':form,
                   'Table_title':'新建' + STR_Name}
        return render(request, 'admin/add.html', context)
    
    form = ModelForm_Category_add(data=request.POST)    
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    
    context = {'form':form,
               'Table_title':'新建' + STR_Name}
    return render(request, 'admin/add.html', context)


def edit(request, nid):
    if request.method == 'GET':
        edit_data = Models_Category.objects.filter(id=nid).first()
        form = ModelForm_Category_edit(instance=edit_data)
        context = {'form':form,
                   'Table_title':'修改' + STR_Name}
        return render(request, 'admin/edit.html', context)
        
    edit_data = Models_Category.objects.filter(id=nid).first()
    form = ModelForm_Category_edit(data=request.POST, instance=edit_data)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    
    context = {'form':form,
               'Table_title':'修改' + STR_Name}
    return render(request, 'admin/edit.html', context)


def delete(request):
    nid = request.GET.get('nid')
    Models_Category.objects.filter(id=nid).delete()
    return redirect("/admin/list")

app01/views/depart.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models

from app01.utils.pagination import Pagination
from app01.utils.My_ModelForm import *
from app01.utils.database_data_process import Data_Create

from app01.views.Layout_Function import *

# ！ 常量
STR_Name = '部门信息'

Models_Category = models.Department
ModelForm_Category_list = DepartmentModelForm_list
ModelForm_Category_add = DepartmentModelForm_add
ModelForm_Category_edit = DepartmentModelForm_edit

def list(request):
    # 创建数据
    # Data_Create().Department()

    context = Views_List_HTML().version_1(request, Models_Category, ModelForm_Category_list)
    context['ModelForm_title'] = '新建' + STR_Name
    context['Table_title'] = STR_Name + '列表'
    return render(request, 'depart/list.html', context)


def add(request):
    if request.method == "GET":
        form = ModelForm_Category_add()
        context = {'form':form,
                   'Table_title':'新建' + STR_Name}
        return render(request, 'depart/add.html', context)
    
    form = ModelForm_Category_add(data=request.POST)    
    if form.is_valid():
        form.save()
        return redirect('/depart/list/')
    
    context = {'form':form,
               'Table_title':'新建' + STR_Name}
    return render(request, 'depart/add.html', context)


def edit(request, nid):
    if request.method == 'GET':
        edit_data = Models_Category.objects.filter(id=nid).first()
        form = ModelForm_Category_edit(instance=edit_data)
        context = {'form':form,
                   'Table_title':'修改' + STR_Name}
        return render(request, 'depart/edit.html', context)
        
    edit_data = Models_Category.objects.filter(id=nid).first()
    form = ModelForm_Category_edit(data=request.POST, instance=edit_data)
    if form.is_valid():
        form.save()
        return redirect('/depart/list/')
    
    context = {'form':form,
               'Table_title':'修改' + STR_Name}
    return render(request, 'depart/edit.html', context)


def delete(request):
    nid = request.GET.get('nid')
    Models_Category.objects.filter(id=nid).delete()
    return redirect("/depart/list")

app01/views/order.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models
from django.views.decorators.csrf import csrf_exempt
from app01.utils.pagination import Pagination
from app01.utils.My_ModelForm import *
from app01.utils.database_data_process import Data_Create
from app01.views.Layout_Function import *
from django.http import JsonResponse
import json
import random
from datetime import datetime

# ！ 常量
STR_Name = '订单信息'

Models_Category = models.Order
ModelForm_Category_list = OrderModelForm_list
ModelForm_Category_add = OrderModelForm_add
ModelForm_Category_edit = OrderModelForm_edit



def list(request):
    # 创建数据
    # Data_Delete().Delete(Models_Category)
    # Data_Create().PrettyNum()

    context = Views_List_HTML().version_1(request, Models_Category, ModelForm_Category_list)
    context['ModelForm_title'] = '新建' + STR_Name
    context['Table_title'] = STR_Name + '列表'
    context['form'] = ModelForm_Category_add()
    return render(request, 'order/list.html', context)


@csrf_exempt
def add(request):
    form = ModelForm_Category_add(data=request.POST)
    if form.is_valid():
        form.instance.oid = datetime.now().strftime('%Y%m%d%H%M%S') + str(random.randint(1000, 9999))
        form.instance.admin_id = request.session['info']['id']
        
        form.save()
        data_list = {'status':True}
        return JsonResponse(data_list)
        
    data_list = {'status':False, 'errors': form.errors}
    return JsonResponse(data_list)


def edit_normal(request, nid):
    if request.method == 'GET':
        edit_data = Models_Category.objects.filter(id=nid).first()
        form = ModelForm_Category_edit(instance=edit_data)
        context = {'form':form,
                   'Table_title':'修改' + STR_Name}
        return render(request, 'order/edit.html', context)
        
    edit_data = Models_Category.objects.filter(id=nid).first()
    form = ModelForm_Category_edit(data=request.POST, instance=edit_data)
    if form.is_valid():
        form.save()
        return redirect('/order/list/')
    
    context = {'form':form,
               'Table_title':'修改' + STR_Name}
    return render(request, 'order/edit.html', context)


def edit_ajax(request):
    data_list = {'status':True, 'errors': 0, 'page_data':0}
    uid = request.GET.get('uid')
    edit_data = Models_Category.objects.filter(id=uid).first()
    
    if not edit_data:
        data_list['status'] = False
        data_list['errors'] = '数据不存在'
        return JsonResponse(data_list)
    
    # 方法1：对象中取值
    # data_list['page_data'] = {
    #     'name' : edit_data.name,
    #     'price' : edit_data.price,
    #     'status' : edit_data.status,
    # }
    
    # 方法2：直接取到数值
    data_list['page_data'] = Models_Category.objects.filter(id=uid).values('name', 'price', 'status').first()
    
    return JsonResponse(data_list)


@csrf_exempt
def edit_ajax_return(request):
    data_list = {'status':True, 'errors': 0, 'tips':0}
    uid = request.GET.get('uid')
    edit_data = Models_Category.objects.filter(id=uid).first()
    
    if not edit_data:
        data_list['status'] = False
        data_list['tips'] = '数据不存在'
        return JsonResponse(data_list)
    
    
    form = ModelForm_Category_edit(data=request.POST, instance=edit_data)
    if form.is_valid():
        form.save()
        data_list = {'status':True}
        return JsonResponse(data_list)
        
    data_list = {'status':False, 'errors': form.errors}
    return JsonResponse(data_list)


def delete_normal(request):
    nid = request.GET.get('nid')
    Models_Category.objects.filter(id=nid).delete()
    return redirect("/order/list")


def delete_ajax(request):
    data_list = {'status':True, 'errors': 0}
    uid = request.GET.get('uid')
    is_exists =  Models_Category.objects.filter(id=uid).exists()
    if not is_exists:
        data_list['status'] = False
        data_list['errors'] = '数据不存在'
    
    Models_Category.objects.filter(id=uid).delete()
    return JsonResponse(data_list)

app01/views/prettynum.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models

from app01.utils.pagination import Pagination
from app01.utils.My_ModelForm import *
from app01.utils.database_data_process import Data_Create

from app01.views.Layout_Function import *

# ！ 常量
STR_Name = '靓号信息'

Models_Category = models.PrettyNum

ModelForm_Category_list = PrettynumModelForm_list
ModelForm_Category_add = PrettynumModelForm_add
ModelForm_Category_edit = PrettynumModelForm_edit

def list(request):
    # 创建数据
    # Data_Delete().Delete(Models_Category)
    # Data_Create().PrettyNum()

    context = Views_List_HTML().version_1(request, Models_Category, ModelForm_Category_list)
    context['ModelForm_title'] = '新建' + STR_Name
    context['Table_title'] = STR_Name + '列表'
    return render(request, 'prettynum/list.html', context)


def add(request):
    if request.method == "GET":
        form = ModelForm_Category_add()
        context = {'form':form,
                   'Table_title':'新建' + STR_Name}
        return render(request, 'prettynum/add.html', context)
    
    form = ModelForm_Category_add(data=request.POST)    
    if form.is_valid():
        form.save()
        return redirect('/prettynum/list/')
    
    context = {'form':form,
               'Table_title':'新建' + STR_Name}
    return render(request, 'prettynum/add.html', context)


def edit(request, nid):
    if request.method == 'GET':
        edit_data = Models_Category.objects.filter(id=nid).first()
        form = ModelForm_Category_edit(instance=edit_data)
        context = {'form':form,
                   'Table_title':'修改' + STR_Name}
        return render(request, 'prettynum/edit.html', context)
        
    edit_data = Models_Category.objects.filter(id=nid).first()
    form = ModelForm_Category_edit(data=request.POST, instance=edit_data)
    if form.is_valid():
        form.save()
        return redirect('/prettynum/list/')
    
    context = {'form':form,
               'Table_title':'修改' + STR_Name}
    return render(request, 'prettynum/edit.html', context)


def delete(request):
    nid = request.GET.get('nid')
    Models_Category.objects.filter(id=nid).delete()
    return redirect("/prettynum/list")

app01/templates/task/add.html
{% extends 'layout.html' %}
{% block content %}

    <div class="container">

        <div style="margin-bottom: 10px;">
            <a class="btn btn-success" href="/task/list/" target="_blank">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                {{ ModelForm_title }}
            </a>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                {{ Table_title }}
            </div>

            <div class="panel-body">
                <form id="form_add" novalidate>
                    {% for field in data_list %}
                        <div class="form-group">
                            <label> {{ field.label }} </label>
                            {{ field }}
                            <span class="error-msg" style="color: red;"></span>
                        </div>
                    {% endfor %}
                    <button id="btn_add" type="button" class="btn btn-primary"> 提交 </button>
                </form>
            </div>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript">

        $(function () {
            add_event() 
        })

        function add_event() {
            $('#btn_add').click( function () {

                // 清空错误信息提示栏
                $('.error-msg').empty()

                $.ajax({
                    url: '/task/add_ajax/',
                    type: 'post',
                    data: $('#form_add').serialize(),
                    success:function(res){
                        if (res.status) {
                            alert('添加成功');
                        } else{
                            // 循环res.errors:键名为name，值名为data
                            $.each(res.errors, function(name, data){
                                // console.log(name, data)
                                $('#id_' + name).next().text(data[0]);
                            })
                        }            
                    }
                })
            })
        }
 
    </script>
{% endblock %}

app01/templates/task/edit.html
{% extends 'layout.html' %}
{% block content %}

<!-- ! 内容部分 -->
<div>
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{{ Table_title }}</h3>
			</div>
			<div class="panel-body">
				<form method="post" novalidate>
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							<label>{{ field.label }}</label>
							{{ field }}
							<span style="color: red;">{{ field.errors.0 }}</span> 
						</div>
					{% endfor %}

					<button type="submit" class="btn btn-primary">提 交</button>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

app01/templates/task/list.html
{% extends 'layout.html' %}
{% block content %}

<!-- ! 内容部分 -->
<div>
	<div class="container">
		<div style="margin-bottom: 50px;">
			<!-- 页面数据搜索框 -->
			<!-- ！前端参数：search_result，所在地 -->
			<!-- ！GET形式传参后端：search_data，用于筛选数据 -->
			{% include 'layout_search_bar.html' %}
		</div>

		<!-- 表格展示区域 -->
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">
				<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
				{{ Table_title }}
			</div>

			<!-- Table -->
			<table class="table table-bordered text-center">
				<thead>
					<tr>
						<th class="text-center">ID</th>
						<th class="text-center">任务级别</th>
						<th class="text-center">任务标题</th>
						<th class="text-center">任务内容</th>
						<th class="text-center">负责人</th>
						<th class="text-center">操作</th>
					</tr>
				</thead>
				<tbody>
					{% for items in data_list %}
					<tr>
						<td class="text-center">{{ items.id }}</td>
						<td class="text-center">{{ items.get_level_display }}</td>
						<td class="text-center">{{ items.task_title }}</td>
						<td class="text-center">{{ items.task_content }}</td>
						<td class="text-center">{{ items.Person_in_Charge.name  }}</td>

						<td class="text-center">
							<a href="/task/{{ items.id }}/edit/" class="btn btn-primary btn-xs">
								编辑
							</a>
							<a href="/task/delete/?nid={{ items.id }}" class="btn btn-danger btn-xs">
								删除
							</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

	</div>
</div>

{% endblock %}

{% block page_sep %}
<ul class="pagination">
	{{ page_string }}
</ul>

<!-- ！GET形式传参后端：page，用于页码跳转 -->
{% include 'layout_page_bar.html' %}
{% endblock %}